"""Assemble deck/slide_outline.md from the results catalog.

M6. Reads the latest run per scenario and writes a slide outline (verdict +
metrics + clip references) for the PowerPoint. The hero clips (photoreal Blender
renders, host-side) are flagged for the scenarios in HERO_DEFAULT.

    python -m deck.build_deck            # -> deck/slide_outline.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

from catalog.reader import latest_per_scenario
from sim.config import REPO_ROOT

# Recommended scenarios for the Blender OptiX hero treatment (host-side).
HERO_DEFAULT = {"droid_replay_reach_check", "human_clearance_pickplace"}


def _fmt(value: object, digits: int = 3) -> str:
    return f"{value:.{digits}f}" if isinstance(value, (int, float)) else "—"


def build_outline(rows: list[dict], hero: set[str]) -> str:
    lines: list[str] = []
    lines.append("# Robot-Cell Digital Twin — slide outline\n")
    lines.append("_Auto-generated by `make report` (deck/build_deck.py) from the "
                 "results catalog. Edit freely; re-run to refresh._\n")

    lines.append("## 1. Title")
    lines.append("- **Robot-Cell Digital Twin — Scenario Verifier**")
    lines.append("- Simulate work-cell scenarios → auto-verify → annotated video.\n")

    lines.append("## 2. Honest scope")
    lines.append("- Offline simulation + scenario verifier in a digital-twin *style* —")
    lines.append("  **not** a live, bidirectionally-synced industrial twin.")
    lines.append("- Safety thresholds are **illustrative** (not ISO 10218 / ISO/TS 15066 "
                 "certified).\n")

    if not rows:
        lines.append("## 3. (No catalog rows yet)")
        lines.append("- Run `make scenarios` / `make verify` / `make render` first.\n")
        return "\n".join(lines)

    for i, r in enumerate(rows, start=3):
        sid = r["scenario_id"]
        verdict = r["verdict"]
        icon = "✅" if verdict == "PASS" else "❌"
        is_hero = sid in hero
        lines.append(f"## {i}. {sid} — {icon} {verdict}" + ("  *(hero clip)*" if is_hero else ""))
        lines.append(f"- reach ok: **{r.get('reach_ok')}** · "
                     f"cycle time: **{_fmt(r.get('cycle_time_s'), 2)} s** · "
                     f"min clearance: **{_fmt(r.get('min_clearance_m'), 3)} m**")
        clip = r.get("clip_path")
        lines.append(f"- overlay clip: `{clip}`" if clip else "- overlay clip: _(run `make render`)_")
        if is_hero:
            hero_clip = r.get("hero_clip_path")
            lines.append(f"- hero clip: `{hero_clip}`" if hero_clip
                         else "- hero clip: _(render on the Windows host — see render/blender/)_")
        lines.append("")

    n = len(rows)
    lines.append(f"## {n + 3}. Roadmap")
    lines.append("- Isaac Sim photoreal · live-sync true twin · fleet monitoring "
                 "(see docs/03-finalization.md).\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Assemble the deck slide outline (M6).")
    parser.add_argument("--db", default=str(REPO_ROOT / "outputs" / "catalog.sqlite"))
    parser.add_argument("--out", default=str(REPO_ROOT / "deck" / "slide_outline.md"))
    args = parser.parse_args()

    rows = latest_per_scenario(Path(args.db))
    outline = build_outline(rows, HERO_DEFAULT)
    Path(args.out).write_text(outline, encoding="utf-8")
    print(f"[deck] wrote {args.out} ({len(rows)} scenario slide(s))")
    if rows:
        heroes = [r["scenario_id"] for r in rows if r["scenario_id"] in HERO_DEFAULT]
        print(f"[deck] hero clips flagged: {heroes or '(none of the recommended present)'}")


if __name__ == "__main__":
    main()
